### ISSUE TITLE
Android build fails on recent NDK versions

### ISSUE THREAD

**Issue by mvglasow** [navit-gps/navit#1043]
After upgrading from NDK 18.1.5063045 to 21.0.6113669, the Android build fails with an error:

```
  In file included from /home/me/src/navit/navit/support/gettext_intl/dcigettext.c:91:
  In file included from ../../../../../support/gettext_intl/gettextP.h:206:
  /home/me/src/navit/navit/support/gettext_intl/dcigettext.c:160:14: warning: this function declaration is not a prototype [-Wstrict-prototypes]
  char *getcwd ();
               ^
                void
  /home/me/src/navit/navit/support/gettext_intl/dcigettext.c:160:7: error: redeclaration of 'getcwd' must have the 'overloadable' attribute
  char *getcwd ();
        ^
  /home/me/tools/android-sdk-linux_86/ndk/21.0.6113669/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits/fortify/unistd.h:105:7: note: previous overload of function is here
  char* getcwd(char* const __pass_object_size buf, size_t size)
        ^
```

Apparently recent versions of the NDK (starting somewhere between 18.1 and 21.0) supply an implementation of `getcwd`, which clashes with our dummy, and we need to work around that. Anyone have an idea how to fix this?

**Comment by jandegr** [comment]
hi,

I added `#if !(defined(__clang__) && defined(__BIONIC_FORTIFY))` before https://github.com/navit-gps/navit/blob/trunk/navit/support/gettext_intl/dcigettext.c#L160
But it is quite a while ago (5 months) I did that and I don't remember the rationale of it anymore.
Maybe this is not good at all or there are better solutions so I am posting this here just for what it is worth.

**Comment by mvglasow** [comment]
Did you commit any fixes regarding this? master (as of 37f22db) still seems to be affected. I tried NDK 21 and 22, both of which fail with the error message above, whereas NDK 18 still works.

**Comment by lains** [comment]
Hello @mvglasow, I have faced the same issue also on my build machine (that uses android-ndk-r21d).
As a workaround, I commented out line 160 in navit/navit/support/gettext_intl/dcigettext.c to be able to biuld:
https://github.com/navit-gps/navit/blob/6b48a55a12339c6fe27ec4b0607bfe1e93b830ac/navit/support/gettext_intl/dcigettext.c#L160

**Comment by mvglasow** [comment]
It would make sense to `#ifdef` it out then if we detect we already have a function by that name (or alternatively we are building for Android and our NDK is above a certain version). Maybe the conditionals jandegr used would work for that.

I'm trying to make sense of the conditionals surrounding the line:

* if `_LIBC` is not defined
* and not `!defined HAVE_GETCWD` (btw, is `#if !defined FOO` any different from `#ifndef FOO`?)
* and `VMS` evaluates to false

Not sure I understand the conditionals and definitions correctly, but the `getcwd` prototype would get added when we are not building against libc, `HAVE_GETCWD` is defined (i.e. we **do** have getcwd already??) and `VMS` is false (whatever that means).

Also, the NDK prototype has a different signature than the one we add in line 160 (ours has no arguments, the NDK one takes a buffer and a size)—not sure about the consequences here. But I’ll try to figure out where this call is used (and what arguments are passed to it), and run the fix through CI to see what happens.

**Comment by mvglasow** [comment]
There are two uses of this function:

https://github.com/navit-gps/navit/blob/6b48a55a12339c6fe27ec4b0607bfe1e93b830ac/navit/support/gettext_intl/dcigettext.c#L550

and

https://github.com/navit-gps/navit/blob/6b48a55a12339c6fe27ec4b0607bfe1e93b830ac/navit/main.c#L362

and in both cases, two arguments are given, so the signature should not be a problem.

With the extra conditionals suggested by jandegr, the build succeeds both against NDK 21 (which previously had issues) and also after downgrading to NDK 18. Just need to run 15a526e5 through CI.

**Comment by mvglasow** [comment]
CI has passed and the PR’s out. Looks like this fixed it with no regressions. Thanks to all!
