### ISSUE TITLE
gpsd problem

### ISSUE THREAD

**Issue by charlescurley** [navit-gps/navit#671]
Here's the problem:

```
charles@hawk:~/versioned/navit-build/navit$ ./navit -c ~/projects/home/.navit/navit.xml
Running from source directory
config file n is set to `/home/charles/projects/home/.navit/navit.xml'
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./navit...done.
Attaching to program: /home/charles/versioned/navit-build/navit/navit, process 30125
[New LWP 30126]
[New LWP 30127]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fda065e704a in __GI___waitpid (pid=30128, stat_loc=stat_loc@entry=0x7fffbb960190, options=options@entry=0)
    at ../sysdeps/unix/sysv/linux/waitpid.c:29
29	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
#0  0x00007fda065e704a in __GI___waitpid (pid=30128, stat_loc=stat_loc@entry=0x7fffbb960190, options=options@entry=0)
    at ../sysdeps/unix/sysv/linux/waitpid.c:29
#1  0x00007fda0656e0ab in do_system (line=line@entry=0x7fffbb9602f0 "gdb -ex bt -ex detach -ex quit ./navit 30125")
    at ../sysdeps/posix/system.c:148
#2  0x00007fda0656e48a in __libc_system (line=line@entry=0x7fffbb9602f0 "gdb -ex bt -ex detach -ex quit ./navit 30125")
    at ../sysdeps/posix/system.c:184
#3  0x000055fb39f12b9e in sigsegv (sig=<optimized out>) at /home/charles/versioned/navit/navit/debug.c:83
#4  <signal handler called>
#5  0x000055fb39f04cbd in iso8601_to_secs (iso8601=iso8601@entry=0x0) at /home/charles/versioned/navit/navit/util.c:321
#6  0x000055fb39f04345 in tracking_update (tr=tr@entry=0x55fb3b730b30, v=<optimized out>, vehicleprofile=<optimized out>, 
    pro=pro@entry=projection_mg) at /home/charles/versioned/navit/navit/track.c:717
#7  0x000055fb39f28b49 in navit_vehicle_update_position (this_=0x55fb3b4fe700, nv=0x55fb3b72be60)
    at /home/charles/versioned/navit/navit/navit.c:3153
#8  0x000055fb39f0cef0 in callback_list_call_attr (l=<optimized out>, type=attr_position_coord_geo, pcount=0, p=0x7fffbb960bf0)
    at /home/charles/versioned/navit/navit/callback.c:229
#9  0x000055fb39f0cfb0 in callback_list_call_attr_args (cbl=<optimized out>, type=type@entry=attr_position_coord_geo, 
    count=count@entry=0) at /home/charles/versioned/navit/navit/callback.c:245
#10 0x00007fd9f6bd1906 in vehicle_gpsd_callback (len=<optimized out>, buf=<optimized out>, data=0x55fb3b728b30)
    at /home/charles/versioned/navit/navit/vehicle/gpsd/vehicle_gpsd.c:202
#11 vehicle_gpsd_io (priv=<optimized out>) at /home/charles/versioned/navit/navit/vehicle/gpsd/vehicle_gpsd.c:343
#12 0x000055fb39f0ce80 in callback_call_args (cb=<optimized out>, count=count@entry=0)
    at /home/charles/versioned/navit/navit/callback.c:212
#13 0x000055fb39f09ec0 in event_glib_call_watch (iochan=<optimized out>, condition=<optimized out>, t=<optimized out>)
    at /home/charles/versioned/navit/navit/event_glib.c:56
#14 0x00007fda074716aa in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007fda07471a60 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---q
Quit
Detaching from program: /home/charles/versioned/navit-build/navit/navit, process 30125
charles@hawk:~/versioned/navit-build/navit$ 
```
Last commit for navit/vehicle/gpsd/vehicle_gpsd.c was

```
commit 567a02aa949dfa34f7b2c2246c6eb6f8818fdf01
Author: Joseph Herlant <aerostitch@users.noreply.github.com>
Date:   Wed May 30 08:43:42 2018 -0700

    Cleanup:global:force the re-attach the return type to the function declaration (#605)
```
    
Falling back to that for testing & possible bisection.

Nope, not the change!!

Fell back to 60bc2797f0bd71d87a4eece306e2368afe2a8866:
```
commit 60bc2797f0bd71d87a4eece306e2368afe2a8866
Author: Sebastian Leske <sebastian.leske@sleske.name>
Date:   Mon Oct 31 15:06:16 2016 +0100

    Refactor:core:For plugins, use term 'category' instead of 'type'.
    
    Use the term 'category' for all plugins with the same API (GUI plugins,
    map plugins etc.). This used to be called 'type', which was confusing,
    because in the XML config, 'type' refers to what is called 'name' in the
    code.
```
So the problem is somewhere between the two.

Checked out trunk again, built and ran it:
```
charles@hawk:~/versioned/navit-build/navit$ Running from source directory
config file n is set to `/home/charles/projects/home/.navit/navit.xml'
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./navit...done.
Attaching to program: /home/charles/versioned/navit-build/navit/navit, process 25851
[New LWP 25852]
[New LWP 25853]
^C
```
I started a bisect. The log is below. The bisect was inconclusive. On reason is that the problem was introduced before all the re-indenting (or possibly during it), making the necessary code comparisons harder to do.

My build process is to have two terminals open, one for managing the repo, at ~/versioned/navit. The other is for building.
```
$ cd ~/versioned/ && rm -r navit-build/ && mkcd navit-build
$ cmake ../navit
$ make
$ cd navit && ln -s ~/.navit/center.txt
$ ./navit -c ~/projects/home/.navit/navit.xml
--------------------------------------------------

--------------------------------------------------
git co trunk
git bisect start
git bisect bad
git bisect good 60bc2797f0bd71d87a4eece306e2368afe2a8866
Bisecting: 348 revisions left to test after this (roughly 9 steps)
[ba7a03173c3c075467f09d132fa0f2f293795c71] Cleanup old xpm icons (#292)
charles@hawk:~/versioned/navit$ git bisect good
Bisecting: 171 revisions left to test after this (roughly 8 steps)
[16b8f12237b20d9d9775c18e3c664f26ed3748e3] Merge branch 'trunk' into fix_compiler_warning
charles@hawk:~/versioned/navit$ git bisect good
Bisecting: 84 revisions left to test after this (roughly 7 steps)
[03f3aa8637fff3e8e09d3bde21b28654454011fd] Merge pull request #551 from navit-gps/fix_log_replay
charles@hawk:~/versioned/navit$ git bisect bad
Bisecting: 43 revisions left to test after this (roughly 6 steps)
[2e2fa838157e09341f3441c14ca4b61bb0fcc362] Update:changelog:Update CHANGELOG.md and add configurations for gitchangelog script (#445)
charles@hawk:~/versioned/navit$ git bisect good
Bisecting: 21 revisions left to test after this (roughly 5 steps)
[4231cac78eebbc761a4a356292aa79693384254f] fix:core:Fixing dbg() change introduced in 221f783ea1caaaab2f5ceadc6b0fb3e720aac3df (#560)
charles@hawk:~/versioned/navit$ git bisect good
Bisecting: 10 revisions left to test after this (roughly 4 steps)
[3de4a6cccf934cbd169e8189b782f440b3dd04d0] fix:vehicle_android:Doc update (#571)
charles@hawk:~/versioned/navit$ git bisect good
Bisecting: 5 revisions left to test after this (roughly 3 steps)
[de8303d46df6fc023fcbaa3c729f9793e34068ed] Fixed typos
charles@hawk:~/versioned/navit$ git bisect bad
Bisecting: 2 revisions left to test after this (roughly 1 step)
[f0b46b6bccf68ae233e1209d1854b1885cf62188] Updated header
```
Compilation at this step failed:
```
--------------------------------------------------
[  2%] Building C object navit/CMakeFiles/navit_core.dir/transform.c.o
[  2%] Building C object navit/CMakeFiles/navit_core.dir/track.c.o
/home/charles/versioned/navit/navit/track.c: In function ‘tracking_update’:
/home/charles/versioned/navit/navit/track.c:1229:0: error: unterminated argument list invoking macro "dbg"
 }
 
/home/charles/versioned/navit/navit/track.c:675:3: error: ‘dbg’ undeclared (first use in this function)
   dbg(lvl_error,"failed to get position data %d %d %d %d\n",
   ^~~
/home/charles/versioned/navit/navit/track.c:675:3: note: each undeclared identifier is reported only once for each function it appears in
/home/charles/versioned/navit/navit/track.c:675:3: error: expected ‘)’ at end of input
/home/charles/versioned/navit/navit/track.c:672:2: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  if (!vehicle_get_attr(tr->vehicle, attr_position_speed, &speed_attr, NULL) ||
  ^~
/home/charles/versioned/navit/navit/track.c:1229:0: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
 }
 
/home/charles/versioned/navit/navit/track.c:675:3: error: expected declaration or statement at end of input
   dbg(lvl_error,"failed to get position data %d %d %d %d\n",
   ^~~
/home/charles/versioned/navit/navit/track.c:658:16: warning: unused variable ‘direction’ [-Wunused-variable]
  double speed, direction;
                ^~~~~~~~~
/home/charles/versioned/navit/navit/track.c:658:9: warning: unused variable ‘speed’ [-Wunused-variable]
  double speed, direction;
         ^~~~~
/home/charles/versioned/navit/navit/track.c:657:83: warning: unused variable ‘static_distance’ [-Wunused-variable]
  struct attr valid,speed_attr,direction_attr,coord_geo,lag,time_attr,static_speed,static_distance;
                                                                                   ^~~~~~~~~~~~~~~
/home/charles/versioned/navit/navit/track.c:657:70: warning: unused variable ‘static_speed’ [-Wunused-variable]
  struct attr valid,speed_attr,direction_attr,coord_geo,lag,time_attr,static_speed,static_distance;
                                                                      ^~~~~~~~~~~~
/home/charles/versioned/navit/navit/track.c:657:60: warning: unused variable ‘time_attr’ [-Wunused-variable]
  struct attr valid,speed_attr,direction_attr,coord_geo,lag,time_attr,static_speed,static_distance;
                                                            ^~~~~~~~~
/home/charles/versioned/navit/navit/track.c:657:56: warning: unused variable ‘lag’ [-Wunused-variable]
  struct attr valid,speed_attr,direction_attr,coord_geo,lag,time_attr,static_speed,static_distance;
                                                        ^~~
/home/charles/versioned/navit/navit/track.c:656:15: warning: unused variable ‘cin’ [-Wunused-variable]
  struct coord cin;
               ^~~
/home/charles/versioned/navit/navit/track.c:655:15: warning: unused variable ‘lpnt’ [-Wunused-variable]
  struct coord lpnt;
               ^~~~
/home/charles/versioned/navit/navit/track.c:654:18: warning: unused variable ‘time’ [-Wunused-variable]
  int i,value,min,time;
                  ^~~~
/home/charles/versioned/navit/navit/track.c:654:14: warning: unused variable ‘min’ [-Wunused-variable]
  int i,value,min,time;
              ^~~
/home/charles/versioned/navit/navit/track.c:654:8: warning: unused variable ‘value’ [-Wunused-variable]
  int i,value,min,time;
        ^~~~~
/home/charles/versioned/navit/navit/track.c:654:6: warning: unused variable ‘i’ [-Wunused-variable]
  int i,value,min,time;
      ^
/home/charles/versioned/navit/navit/track.c:653:24: warning: unused variable ‘t’ [-Wunused-variable]
  struct tracking_line *t;
                        ^
At top level:
/home/charles/versioned/navit/navit/track.c:602:1: warning: ‘tracking_value’ defined but not used [-Wunused-function]
 tracking_value(struct tracking *tr, struct tracking_line *t, int offset, struct coord *lpnt, int min, int flags)
 ^~~~~~~~~~~~~~
/home/charles/versioned/navit/navit/track.c:461:1: warning: ‘tracking_doupdate_lines’ defined but not used [-Wunused-function]
 tracking_doupdate_lines(struct tracking *tr, struct coord *pc, enum projection pro)
 ^~~~~~~~~~~~~~~~~~~~~~~
/home/charles/versioned/navit/navit/track.c:126:1: warning: ‘tracking_init_cdf’ defined but not used [-Wunused-function]
 tracking_init_cdf(struct cdf_data *cdf, int hist_size)
 ^~~~~~~~~~~~~~~~~
navit/CMakeFiles/navit_core.dir/build.make:1190: recipe for target 'navit/CMakeFiles/navit_core.dir/track.c.o' failed
make[2]: *** [navit/CMakeFiles/navit_core.dir/track.c.o] Error 1
CMakeFiles/Makefile2:173: recipe for target 'navit/CMakeFiles/navit_core.dir/all' failed
make[1]: *** [navit/CMakeFiles/navit_core.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
charles@hawk:~/versioned/navit-build$ 
```
I reverted the code back to prior state and got a good build.
```
	if (!vehicle_get_attr(tr->vehicle, attr_position_speed, &speed_attr, NULL) ||
	    !vehicle_get_attr(tr->vehicle, attr_position_direction, &direction_attr, NULL) ||
	    !vehicle_get_attr(tr->vehicle, attr_position_coord_geo, &coord_geo, NULL)) {
                    dbg(lvl_error,"failed to get position data %d %d %d\n",
                        vehicle_get_attr(tr->vehicle, attr_position_speed, &speed_attr, NULL),
                        vehicle_get_attr(tr->vehicle, attr_position_direction, &direction_attr, NULL),
                        vehicle_get_attr(tr->vehicle, attr_position_coord_geo, &coord_geo, NULL));
                    return;
            }
```
```
charles@hawk:~/versioned/navit$ git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
error: Your local changes to the following files would be overwritten by checkout:
	navit/track.c
Please commit your changes or stash them before you switch branches.
Aborting
charles@hawk:~/versioned/navit$ git diff
charles@hawk:~/versioned/navit$ git bisect bad
Bisecting: a merge base must be tested
[011bb15468b4cb626e9facecba924b04bd494d7f] Fix:CI:Automated upload to playstore (#540)

```
```
charles@hawk:~/versioned/navit$ git bisect log
git bisect start
# bad: [98e7489e1098e22ec13097ea09c2af49a8889a59] build:maptool:Fix cmake CMP0026 warning (#666)
git bisect bad 98e7489e1098e22ec13097ea09c2af49a8889a59
# good: [60bc2797f0bd71d87a4eece306e2368afe2a8866] Refactor:core:For plugins, use term 'category' instead of 'type'.
git bisect good 60bc2797f0bd71d87a4eece306e2368afe2a8866
# good: [ba7a03173c3c075467f09d132fa0f2f293795c71] Cleanup old xpm icons (#292)
git bisect good ba7a03173c3c075467f09d132fa0f2f293795c71
# good: [16b8f12237b20d9d9775c18e3c664f26ed3748e3] Merge branch 'trunk' into fix_compiler_warning
git bisect good 16b8f12237b20d9d9775c18e3c664f26ed3748e3
# bad: [03f3aa8637fff3e8e09d3bde21b28654454011fd] Merge pull request #551 from navit-gps/fix_log_replay
git bisect bad 03f3aa8637fff3e8e09d3bde21b28654454011fd
# good: [2e2fa838157e09341f3441c14ca4b61bb0fcc362] Update:changelog:Update CHANGELOG.md and add configurations for gitchangelog script (#445)
git bisect good 2e2fa838157e09341f3441c14ca4b61bb0fcc362
# good: [4231cac78eebbc761a4a356292aa79693384254f] fix:core:Fixing dbg() change introduced in 221f783ea1caaaab2f5ceadc6b0fb3e720aac3df (#560)
git bisect good 4231cac78eebbc761a4a356292aa79693384254f
# good: [3de4a6cccf934cbd169e8189b782f440b3dd04d0] fix:vehicle_android:Doc update (#571)
git bisect good 3de4a6cccf934cbd169e8189b782f440b3dd04d0
# bad: [de8303d46df6fc023fcbaa3c729f9793e34068ed] Fixed typos
git bisect bad de8303d46df6fc023fcbaa3c729f9793e34068ed
# bad: [f0b46b6bccf68ae233e1209d1854b1885cf62188] Updated header
git bisect bad f0b46b6bccf68ae233e1209d1854b1885cf62188
# bad: [f0b46b6bccf68ae233e1209d1854b1885cf62188] Updated header
git bisect bad f0b46b6bccf68ae233e1209d1854b1885cf62188
charles@hawk:~/versioned/navit$ 

```

**Comment by charlescurley** [comment]
At some point the "lag" option for <vehicle/> went away. But not knowing this, I left it in my navit.xml. And navit bombed at run time. Shouldn't an XML parser simply ignore unused options?

**Comment by jkoan** [comment]
Should be fixed by now, couldn't find any issue in the last time
