### ISSUE TITLE
FTBFS with recent gpsd release

### ISSUE THREAD

**Issue by CameronNemo** [navit-gps/navit#1057]
Trying to build with gpsd 3.21

```
/builddir/navit-0.5.5/navit/vehicle/gpsd/vehicle_gpsd.c: In function 'vehicle_gpsd_callback':
/builddir/navit-0.5.5/navit/vehicle/gpsd/vehicle_gpsd.c:169:28: error: 'struct gps_data_t' has no member named 'status'
  169 |         priv->status = data->status;
      |                            ^~
```

Seems the API was changed again.

**Comment by jkoan** [comment]
See #1039 which has already been queued for 0.5.6. So building trunk should work.

**Comment by CameronNemo** [comment]
Ah, thanks.
